export interface Category {
    id: string;
    title: string;
    slug: string;
    description: string;
    image_url: string;
}

export interface Product {
    id: string;
    title: string;
    slug: string;
    description: string;
    short_description: string;
    price_range: string;
    category_id: string;
    is_featured: boolean;
    specs: { label: string; value: string }[];
    tags: string[];
    images: string[];
}

// Services derived from company.ts
export const CATEGORIES: Category[] = [
    {
        id: 'service-1',
        title: 'Water Treatment Setups',
        slug: 'water-treatment-setups',
        description: 'Complete commercial and industrial water treatment solutions.',
        image_url: '/Images/RO Water purification setup 500lph.mp4',
    },
    {
        id: 'service-2',
        title: 'Reverse Osmosis Filters',
        slug: 'reverse-osmosis-filters',
        description: 'High-quality RO filters for domestic and commercial use.',
        image_url: '/Images/1000lph RO setup.jpeg',
    },
    {
        id: 'service-3',
        title: 'Stainless Steel Products',
        slug: 'stainless-steel-products',
        description: 'Durable custom stainless steel fabrications.',
        image_url: '/Images/s.s product tank 2000l.jpeg',
    },
    {
        id: 'service-4',
        title: 'Industrial Purifiers',
        slug: 'industrial-purifiers',
        description: 'Large scale water purification systems.',
        image_url: '/Images/Reverse Osmosis 3000lph.jpeg',
    },
    {
        id: 'service-5',
        title: 'Milk Processing Equipment',
        slug: 'milk-processing-equipment',
        description: 'Equipment for milk cooling, storage, and processing.',
        image_url: '/Images/milk chillers.mp4',
    },
    {
        id: 'service-6',
        title: 'Water Refill, Milk & Salad ATMs',
        slug: 'atms-vending',
        description: 'Automated vending machines for water, milk, and salad.',
        image_url: '/Images/MilkAtm.jpeg',
    },
    {
        id: 'service-7',
        title: 'Kitchen Equipment',
        slug: 'kitchen-equipment',
        description: 'Professional commercial kitchen appliances and furniture.',
        image_url: '/Images/4 burner cooker.jpeg',
    },
    {
        id: 'service-8',
        title: 'Medical Stainless Steel',
        slug: 'medical-stainless-steel',
        description: 'Hygenic stainless steel equipment for medical use.',
        image_url: '/Images/s.s shelf.jpeg',
    },
    {
        id: 'service-9',
        title: 'Accessories',
        slug: 'accessories',
        description: 'Essential accessories and components.',
        image_url: '/Images/bottle rinser.jpeg',
    },
];

export const PRODUCTS: Product[] = [
    // --- Water Treatment Setups (service-1) ---
    {
        id: '107',
        title: '500LPH RO Complete Setup',
        slug: '500lph-ro-complete',
        description: 'Turnkey 500LPH RO solution including installation components.',
        short_description: 'Ready-to-install 500LPH commercial water purification system',
        price_range: 'Contact for Price',
        category_id: 'service-1',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '500 LPH' },
            { label: 'Type', value: 'Complete Setup' },
        ],
        tags: ['water', 'ro', 'setup'],
        images: ['/Images/500lph RO complete.jpeg', '/Images/500lph RO setup.jpeg'],
    },
    {
        id: '108',
        title: '500LPH RO with Overhead Tank',
        slug: '500lph-ro-overhead-tank',
        description: '500LPH RO system configuration with an integrated overhead tank.',
        short_description: 'Integrated 500LPH RO + storage for continuous water supply',
        price_range: 'Contact for Price',
        category_id: 'service-1',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '500 LPH' },
            { label: 'Features', value: 'Overhead Tank' },
        ],
        tags: ['water', 'ro', 'tank'],
        images: ['/Images/500lph RO with overhead tank.jpeg'],
    },
    {
        id: '113',
        title: 'RO Setup 20LPH with 300L Tank',
        slug: 'ro-setup-20lph-300l-tank',
        description: 'Small scale 20LPH RO setup coupled with a 300L overhead tank.',
        short_description: 'Perfect for homes & small offices - 20LPH with 300L storage',
        price_range: 'Contact for Price',
        category_id: 'service-1',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '20 LPH' },
            { label: 'Tank', value: '300 L' },
        ],
        tags: ['water', 'ro', 'domestic'],
        images: ['/Images/RO Water purification setup 20lph with overheadtank 300l.jpeg'],
    },
    {
        id: '115',
        title: 'RO with Overhead Tank',
        slug: 'ro-overhead-tank-large',
        description: 'Comprehensive RO system installed with large overhead tank storage.',
        short_description: 'RO System with Tank',
        price_range: 'Contact for Price',
        category_id: 'service-1',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'RO + Tank' },
        ],
        tags: ['water', 'ro', 'storage'],
        images: ['/Images/Ro with overhead tank.jpeg'],
    },
    {
        id: '120',
        title: 'Ultrafiltration with Overhead Tank',
        slug: 'uf-overhead-tank',
        description: 'Ultrafiltration system integrated with an overhead tank.',
        short_description: 'UF with Overhead Tank',
        price_range: 'Contact for Price',
        category_id: 'service-1',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'UF + Tank' },
        ],
        tags: ['water', 'uf', 'tank'],
        images: ['/Images/Ultrafiltration with overhead tank.jpeg'],
    },


    // --- Reverse Osmosis Filters (service-2) ---
    {
        id: '109',
        title: 'Digital Undersink Purifier',
        slug: 'digital-undersink-purifier',
        description: 'Modern digital undersink water purifier for sleek kitchens.',
        short_description: 'Smart digital controls for modern kitchen water purification',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Undersink' },
            { label: 'Controls', value: 'Digital' },
        ],
        tags: ['water', 'domestic', 'purifier'],
        images: ['/Images/Digital undersink.jpeg', '/Images/Digital undersink.2.jpeg'],
    },
    {
        id: '110',
        title: 'Domestic RO Undersink',
        slug: 'domestic-ro-undersink',
        description: 'Compact Reverse Osmosis system designed for under-sink installation in homes.',
        short_description: 'Space-saving RO system for clean drinking water at home',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Undersink' },
            { label: 'Usage', value: 'Domestic' },
        ],
        tags: ['water', 'domestic', 'ro'],
        images: ['/Images/Domestic ro undersink.jpeg'],
    },
    {
        id: '104',
        title: '100LPH RO System',
        slug: '100lph-ro-system',
        description: 'Compact 100 Liters Per Hour RO system, suitable for small businesses or large households.',
        short_description: 'Ideal for small businesses & large households - reliable 100LPH capacity',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '100 LPH' },
            { label: 'Type', value: 'RO System' },
        ],
        tags: ['water', 'ro', 'small business'],
        images: ['/Images/100lph ro.jpeg'],
    },
    {
        id: '124',
        title: 'Semi Commercial RO 100LPH',
        slug: 'semi-commercial-ro-100lph',
        description: 'Semi-commercial grade 100LPH Reverse Osmosis system.',
        short_description: '100LPH Semi-Commercial RO',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '100 LPH' },
            { label: 'Type', value: 'Semi-Commercial' },
        ],
        tags: ['water', 'ro', 'semi-commercial'],
        images: ['/Images/semi commercial ro 100lph.jpeg'],
    },
    {
        id: '103',
        title: '1000LPH RO Setup',
        slug: '1000lph-ro-setup',
        description: 'Complete 1000 Liters Per Hour Reverse Osmosis setup for commercial water purification.',
        short_description: 'High-capacity 1000LPH for restaurants, offices & commercial use',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: true,
        specs: [
            { label: 'Capacity', value: '1000 LPH' },
            { label: 'Type', value: 'RO Setup' },
        ],
        tags: ['water', 'ro', 'commercial'],
        images: ['/Images/1000lph RO setup.jpeg'],
    },
    {
        id: '105',
        title: '1500LPH RO Setup',
        slug: '1500lph-ro-setup',
        description: 'High-performance 1500 Liters Per Hour RO purification setup.',
        short_description: 'Industrial-grade 1500LPH purification for heavy-duty applications',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '1500 LPH' },
            { label: 'Type', value: 'RO Setup' },
        ],
        tags: ['water', 'ro', 'commercial'],
        images: ['/Images/1500lph RO setup.jpeg'],
    },
    {
        id: '106',
        title: '500LPH RO System',
        slug: '500lph-ro-system',
        description: 'Standard 500 Liters Per Hour Reverse Osmosis system.',
        short_description: 'Reliable 500LPH reverse osmosis - perfect for mid-size operations',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: true,
        specs: [
            { label: 'Capacity', value: '500 LPH' },
            { label: 'Type', value: 'RO System' },
        ],
        tags: ['water', 'ro', 'commercial'],
        images: ['/Images/500lph RO .jpeg', '/Images/500lph RO .2.jpeg'],
    },
    {
        id: '125',
        title: 'Standard RO 500LPH',
        slug: 'standard-ro-500lph',
        description: 'Standard model 500LPH Reverse Osmosis machine.',
        short_description: 'Standard 500LPH RO',
        price_range: 'Contact for Price',
        category_id: 'service-2',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '500 LPH' },
        ],
        tags: ['water', 'ro', 'standard'],
        images: ['/Images/standard Ro 500lph.jpeg'],
    },


    // --- Stainless Steel Products (service-3) ---
    {
        id: '102',
        title: '10,000 Liters S.S Mounting',
        slug: '10000-liters-ss-mounting',
        description: 'Stainless steel mounting structure for 10,000 liter tanks, ensuring stability and durability.',
        short_description: 'Heavy duty SS mounting for 10kL tanks',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '10,000 Liters' },
            { label: 'Material', value: 'Stainless Steel' },
        ],
        tags: ['mounting', 'tank', 'stainless steel'],
        images: ['/Images/10,000 liters s.s mounting.jpeg'],
    },
    {
        id: '111',
        title: 'Overhead Tank',
        slug: 'overhead-tank',
        description: 'Robust overhead water storage tank.',
        short_description: 'Water storage overhead tank',
        price_range: 'Contact for Price',
        category_id: 'service-3', // Could also be Water Treatment, but is storage
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Storage' },
            { label: 'Installation', value: 'Overhead' },
        ],
        tags: ['water', 'storage', 'tank'],
        images: ['/Images/Overhead tank.jpeg'],
    },
    {
        id: '116',
        title: 'S.S. Tank Boozer',
        slug: 'ss-tank-boozer',
        description: 'Stainless Steel Boozer tank for mobile water transport or storage.',
        short_description: 'Stainless Steel Boozer Tank',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Material', value: 'Stainless Steel' },
            { label: 'Type', value: 'Boozer' },
        ],
        tags: ['water', 'transport', 'stainless steel'],
        images: ['/Images/S.s tank boozer.jpeg', '/Images/s.s boozer tank.2.jpeg'],
    },
    {
        id: '121',
        title: 'Bottle Rinser',
        slug: 'bottle-rinser',
        description: 'Efficient bottle rinsing machine for bottling plants.',
        short_description: 'Industrial Bottle Rinser',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Usage', value: 'Bottling' },
        ],
        tags: ['bottling', 'rinser'],
        images: ['/Images/bottle rinser.jpeg'],
    },
    {
        id: '122',
        title: 'S.S. Product Tank 2000L',
        slug: 'ss-product-tank-2000l',
        description: '2000 Liters Stainless Steel product storage tank.',
        short_description: '2000L SS Product Tank',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '2000 L' },
            { label: 'Material', value: 'Stainless Steel' },
        ],
        tags: ['storage', 'tank', 'stainless steel'],
        images: ['/Images/s.s product tank 2000l.jpeg'],
    },
    {
        id: '123',
        title: 'S.S. Tank Mounting',
        slug: 'ss-tank-mounting',
        description: 'Stainless steel mounting frame for tanks.',
        short_description: 'SS Tank Mounting',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Material', value: 'Stainless Steel' },
        ],
        tags: ['mounting', 'tank'],
        images: ['/Images/s.s tank mounting.jpeg'],
    },
    {
        id: '126',
        title: 'Water Boozer 600L',
        slug: 'water-boozer-600l',
        description: '600 Liters capacity water boozer for transport.',
        short_description: '600L Water Boozer',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '600 L' },
            { label: 'Type', value: 'Boozer' },
        ],
        tags: ['water', 'transport'],
        images: ['/Images/water boozer 600l.jpeg'],
    },
    {
        id: '127',
        title: 'Water Boozer',
        slug: 'water-boozer-generic',
        description: 'Reliable water boozer unit for efficient distribution.',
        short_description: 'Water Boozer Unit',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Boozer' },
        ],
        tags: ['water', 'transport'],
        images: ['/Images/water boozers.jpeg'],
    },
    {
        id: '128',
        title: 'White Clear Tank 1000L',
        slug: 'white-clear-tank-1000l',
        description: 'High visibility white clear tank with 1000L capacity.',
        short_description: '1000L White Clear Tank',
        price_range: 'Contact for Price',
        category_id: 'service-3',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '1000 L' },
            { label: 'Color', value: 'White' },
        ],
        tags: ['storage', 'tank'],
        images: ['/Images/white clear tank 1000l.jpeg'],
    },


    // --- Industrial Purifiers (service-4) ---
    {
        id: '101',
        title: '10 Cubic RO System',
        slug: '10-cubic-ro-system',
        description: 'High capacity 10 cubic Reverse Osmosis water purification system for industrial use.',
        short_description: 'Industrial 10 cubic RO system',
        price_range: 'Contact for Price',
        category_id: 'service-4',
        is_featured: true,
        specs: [
            { label: 'Capacity', value: '10 Cubic' },
            { label: 'Type', value: 'Reverse Osmosis' },
        ],
        tags: ['water', 'ro', 'industrial'],
        images: ['/Images/10 cubic ro.jpeg'],
    },
    {
        id: '112',
        title: '2 Cubic RO System',
        slug: '2-cubic-ro-system',
        description: 'Mid-sized 2 cubic Reverse Osmosis system.',
        short_description: '2 Cubic RO System',
        price_range: 'Contact for Price',
        category_id: 'service-4',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '2 Cubic' },
            { label: 'Type', value: 'Reverse Osmosis' },
        ],
        tags: ['water', 'ro', 'industrial'],
        images: ['/Images/RO 2 cubic.jpeg'],
    },
    {
        id: '114',
        title: '3000LPH Reverse Osmosis',
        slug: '3000lph-reverse-osmosis',
        description: 'Large scale 3000 Liters Per Hour Reverse Osmosis plant.',
        short_description: '3000LPH Industrial RO',
        price_range: 'Contact for Price',
        category_id: 'service-4',
        is_featured: true,
        specs: [
            { label: 'Capacity', value: '3000 LPH' },
            { label: 'Type', value: 'Industrial' },
        ],
        tags: ['water', 'ro', 'industrial'],
        images: ['/Images/Reverse Osmosis 3000lph.jpeg'],
    },
    {
        id: '117',
        title: 'UF Purifier 2000LPH',
        slug: 'uf-purifier-2000lph',
        description: 'Ultrafiltration water purifier with 2000LPH capacity.',
        short_description: '2000LPH Ultrafiltration',
        price_range: 'Contact for Price',
        category_id: 'service-4',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '2000 LPH' },
            { label: 'Technology', value: 'Ultrafiltration' },
        ],
        tags: ['water', 'uf', 'commercial'],
        images: ['/Images/Uf purifier 2000lph.salad.milkAtm.mp4'],
    },
    {
        id: '119',
        title: '4 Cubic Ultrafiltration',
        slug: '4-cubic-ultrafiltration',
        description: 'Large capacity 4 cubic Ultrafiltration system.',
        short_description: '4 Cubic UF System',
        price_range: 'Contact for Price',
        category_id: 'service-4',
        is_featured: true,
        specs: [
            { label: 'Capacity', value: '4 Cubic' },
            { label: 'Technology', value: 'Ultrafiltration' },
        ],
        tags: ['water', 'uf', 'industrial'],
        images: ['/Images/Ultrafiltration 4 cubic.jpeg'],
    },


    // --- Milk Processing Equipment (service-5) ---
    {
        id: '501', // New ID
        title: 'Milk Chillers',
        slug: 'milk-chillers',
        description: 'Efficient milk cooling and chilling systems.',
        short_description: 'Industrial Milk Chillers',
        price_range: 'Contact for Price',
        category_id: 'service-5',
        is_featured: false,
        specs: [
            { label: 'Usage', value: 'Cooling' },
        ],
        tags: ['dairy', 'milk', 'cooling'],
        images: ['/Images/milk chillers.mp4'],
    },


    // --- Water Refill, Milk & Salad ATMs (service-6) ---
    {
        id: '201',
        title: '2 Taps Vending with Rinser',
        slug: '2-taps-vending-rinser',
        description: 'Automatic vending machine featuring 2 taps and a built-in bottle rinser.',
        short_description: '2 Taps Vending + Rinser',
        price_range: 'Contact for Price',
        category_id: 'service-6',
        is_featured: true,
        specs: [
            { label: 'Taps', value: '2' },
            { label: 'Feature', value: 'Rinser' },
        ],
        tags: ['vending', 'water', 'automation'],
        images: ['/Images/2 taps vending with rinser.jpeg', '/Images/2 taps with rinser.jpeg'],
    },
    {
        id: '202',
        title: '2 Taps with Rinser (Fresh Water)',
        slug: '2-taps-rinser-fresh-water',
        description: '2-tap vending station specialized for fresh water dispensing with rinsing capability.',
        short_description: 'Fresh Water Vending Station',
        price_range: 'Contact for Price',
        category_id: 'service-6',
        is_featured: false,
        specs: [
            { label: 'Taps', value: '2' },
            { label: 'Usage', value: 'Fresh Water' },
        ],
        tags: ['vending', 'water'],
        images: ['/Images/2 taps with rinser fresh water.jpeg'],
    },
    {
        id: '203',
        title: '2 Taps with Rinser (Site)',
        slug: '2-taps-rinser-site',
        description: 'On-site installation of 2 taps vending machine with rinser.',
        short_description: '2 Taps Vending Installation',
        price_range: 'Contact for Price',
        category_id: 'service-6',
        is_featured: false,
        specs: [
            { label: 'Taps', value: '2' },
            { label: 'Location', value: 'On-site' },
        ],
        tags: ['vending', 'water', 'site'],
        images: ['/Images/2 taps with rinser site.jpeg'],
    },
    {
        id: '204',
        title: 'Milk ATM',
        slug: 'milk-atm',
        description: 'Hygienic and automated Milk ATM for self-service milk dispensing.',
        short_description: 'Automated Milk ATM',
        price_range: 'Contact for Price',
        category_id: 'service-6',
        is_featured: true,
        specs: [
            { label: 'Type', value: 'Milk ATM' },
            { label: 'Automation', value: 'Full' },
        ],
        tags: ['vending', 'milk', 'dairy'],
        images: ['/Images/MilkAtm.jpeg'],
    },
    {
        id: '205',
        title: 'Salad ATM',
        slug: 'salad-atm',
        description: 'Innovative Salad ATM for keeping salads fresh and dispensing them.',
        short_description: 'Fresh Salad ATM',
        price_range: 'Contact for Price',
        category_id: 'service-6',
        is_featured: true,
        specs: [
            { label: 'Type', value: 'Salad ATM' },
            { label: 'Temp Control', value: 'Cooled' },
        ],
        tags: ['vending', 'salad', 'food'],
        images: ['/Images/salad atm.jpeg', '/Images/Salad atm.2.jpeg'],
    },


    // --- Kitchen Equipment (service-7) ---
    {
        id: '301',
        title: '4 Burner Cooker',
        slug: '4-burner-cooker',
        description: 'Heavy duty commercial 4 burner cooker for high-volume kitchens.',
        short_description: 'Commercial 4 Burner Cooker',
        price_range: 'Contact for Price',
        category_id: 'service-7',
        is_featured: true,
        specs: [
            { label: 'Burners', value: '4' },
            { label: 'Type', value: 'Commercial' },
        ],
        tags: ['kitchen', 'cooking', 'gas'],
        images: ['/Images/4 burner cooker.jpeg'],
    },
    {
        id: '302',
        title: 'Bain Marie',
        slug: 'bain-marie',
        description: 'Stainless steel Bain Marie for keeping food warm and ready to serve.',
        short_description: 'Food Warmer Bain Marie',
        price_range: 'Contact for Price',
        category_id: 'service-7',
        is_featured: false,
        specs: [
            { label: 'Material', value: 'Stainless Steel' },
            { label: 'Usage', value: 'Food Warming' },
        ],
        tags: ['kitchen', 'warming', 'buffet'],
        images: ['/Images/Bein Marie.jpeg'],
    },
    {
        id: '303',
        title: 'Packing Table',
        slug: 'packing-table',
        description: 'Sturdy stainless steel packing table for food preparation or packaging.',
        short_description: 'SS Packing Table',
        price_range: 'Contact for Price',
        category_id: 'service-7',
        is_featured: false,
        specs: [
            { label: 'Material', value: 'Stainless Steel' },
            { label: 'Type', value: 'Table' },
        ],
        tags: ['kitchen', 'table', 'prep'],
        images: ['/Images/packing table.jpeg', '/Images/packing table site.jpeg'],
    },
    {
        id: '305',
        title: 'Single Fryer',
        slug: 'single-fryer',
        description: 'Commercial grade single basket deep fryer.',
        short_description: 'Single Basket Fryer',
        price_range: 'Contact for Price',
        category_id: 'service-7',
        is_featured: false,
        specs: [
            { label: 'Baskets', value: '1' },
            { label: 'Power', value: 'Gas/Electric' },
        ],
        tags: ['kitchen', 'frying', 'cooking'],
        images: ['/Images/single fryer.jpeg', '/Images/single fryer .2.jpeg'],
    },
    {
        id: '306',
        title: 'Three Burner Cooker',
        slug: 'three-burner-cooker',
        description: 'Efficient 3 burner commercial cooker.',
        short_description: '3 Burner Commercial Cooker',
        price_range: 'Contact for Price',
        category_id: 'service-7',
        is_featured: false,
        specs: [
            { label: 'Burners', value: '3' },
            { label: 'Type', value: 'Commercial' },
        ],
        tags: ['kitchen', 'cooking', 'gas'],
        images: ['/Images/three burner cooker.jpeg'],
    },


    // --- Medical Stainless Steel (service-8) ---
    {
        id: '304',
        title: 'S.S. Shelf',
        slug: 'ss-shelf',
        description: 'Durable stainless steel shelving unit for medical or kitchen storage.',
        short_description: 'Stainless Steel Shelf',
        price_range: 'Contact for Price',
        category_id: 'service-8', // Assigned to medical as per service list implication, though could be kitchen
        is_featured: false,
        specs: [
            { label: 'Material', value: 'Stainless Steel' },
            { label: 'Type', value: 'Storage' },
        ],
        tags: ['storage', 'shelf', 'medical'],
        images: ['/Images/s.s shelf.jpeg'],
    },


    // --- Accessories (service-9) ---
    {
        id: '401',
        title: 'DDG Pump 1000',
        slug: 'ddg-pump-1000',
        description: 'High-performance DDG pump with 1000 LPH capacity for water treatment systems.',
        short_description: 'DDG Pump 1000 LPH',
        price_range: 'Contact for Price',
        category_id: 'service-9',
        is_featured: false,
        specs: [
            { label: 'Capacity', value: '1000 LPH' },
            { label: 'Type', value: 'DDG Pump' },
        ],
        tags: ['pump', 'accessories', 'water treatment'],
        images: ['/accessories/ddg pump-1000.jpeg'],
    },
    {
        id: '402',
        title: 'Dosing Pump',
        slug: 'dosing-pump',
        description: 'Precision dosing pump for chemical injection in water treatment applications.',
        short_description: 'Chemical Dosing Pump',
        price_range: 'Contact for Price',
        category_id: 'service-9',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Dosing Pump' },
            { label: 'Application', value: 'Chemical Injection' },
        ],
        tags: ['pump', 'accessories', 'dosing'],
        images: ['/accessories/dosing pump.jpg'],
    },
    {
        id: '403',
        title: 'Filter Housing',
        slug: 'filter-housing',
        description: 'Durable filter housing for water treatment filter cartridges.',
        short_description: 'Filter Housing Unit',
        price_range: 'Contact for Price',
        category_id: 'service-9',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Housing' },
            { label: 'Application', value: 'Filter Cartridges' },
        ],
        tags: ['filter', 'accessories', 'housing'],
        images: ['/accessories/filter housing.jpeg'],
    },
    {
        id: '404',
        title: 'Water Filters',
        slug: 'water-filters',
        description: 'Replacement water filter cartridges for purification systems.',
        short_description: 'Filter Cartridges',
        price_range: 'Contact for Price',
        category_id: 'service-9',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Filter Cartridge' },
            { label: 'Application', value: 'Water Purification' },
        ],
        tags: ['filter', 'accessories', 'replacement'],
        images: ['/accessories/filters.jpeg'],
    },
    {
        id: '405',
        title: 'HP Pump',
        slug: 'hp-pump',
        description: 'High-pressure pump for reverse osmosis and water treatment systems.',
        short_description: 'High-Pressure Pump',
        price_range: 'Contact for Price',
        category_id: 'service-9',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'HP Pump' },
            { label: 'Application', value: 'RO Systems' },
        ],
        tags: ['pump', 'accessories', 'high-pressure'],
        images: ['/accessories/hp pump.jpeg'],
    },
    {
        id: '406',
        title: 'Solenoid Valves',
        slug: 'solenoid-valves',
        description: 'Automatic solenoid valves for water treatment and control systems.',
        short_description: 'Solenoid Control Valves',
        price_range: 'Contact for Price',
        category_id: 'service-9',
        is_featured: false,
        specs: [
            { label: 'Type', value: 'Solenoid Valve' },
            { label: 'Application', value: 'Automation' },
        ],
        tags: ['valve', 'accessories', 'automation'],
        images: ['/accessories/solenoid valves.jpg'],
    },
];
